name: Android Kotlin CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛠 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 📦 Set up Gradle cache (升级到 `v3`)
        uses: gradle/gradle-build-action@v3

      - name: 🚀 Build Debug APK
        run: ./gradlew assembleDebug

      - name: 📝 Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: 🚀 Upload APK as Artifact (升级 `upload-artifact@v4`)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
